# Generated by Django 4.1.4 on 2023-08-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Address',
            field=models.TextField(max_length=50),
        ),
    ]
